dist: trusty
sudo: required

language: rust

rust:
  - stable
  - beta
  - nightly

before_script:
  - rustup component add clippy

script:
  - RUSTFLAGS="-D warnings" cargo build
  - RUSTFLAGS="-D warnings" cargo test
  - RUSTFLAGS="-D warnings" cargo clippy
