[package]
name = "factorio"
version = "1.1.0"
description = "A factory library for Rust, inspired by FactoryBot. 🤖"
license = "MIT"
authors = ["Hugo Almeida <hugofalmeida@gmail.com>", "Michael Killough <michaeljkillough@gmail.com>"]
repository = "https://github.com/GriffinHeart/factorio"
keywords = ["factory", "testing", "test", "fixture"]
categories = ["development-tools::testing"]
readme = "README.md"
edition = "2018"

[badges]
travis-ci = { repository = "mjkillough/factori", branch = "master" }

[dependencies]
factori-impl = { version = "1.1.0", path = "./factori-impl" }
